### ISSUE TITLE
Message: Connection Refused Help Needed

### ISSUE THREAD

**Issue by sakyb7** [FortyNorthSecurity/EyeWitness#355]
have problem while running eyewitness..
have on attachment..

```
################################################################################
#                                  EyeWitness                                  #
################################################################################
#           FortyNorth Security - https://www.fortynorthsecurity.com           #
################################################################################

Starting Web Requests (6 Hosts)
Message: connection refused
```

![1](https://user-images.githubusercontent.com/42310984/45837157-ab71f780-bcdc-11e8-9bdf-4f5258841deb.png)

## Geckodrive logs
![2](https://user-images.githubusercontent.com/42310984/45837159-add45180-bcdc-11e8-906e-281ab73330da.png)

**Comment by ChrisTruncer** [comment]
Can you provide the hosts that you are scanning which results in that message?

**Comment by sakyb7** [comment]
Just testing eyewitness its working or not

`site.txt`

```
google.com
evil.com
fb.com
youtube.com
hackerone.com
lob.com

```

**Comment by ChrisTruncer** [comment]
Can you give more information, what distro are you running this on, or anything else? Did you run the setup script?

Please provide all the information requested of you for when you open a github issue. I cannot recreate this issue on my end.

**Comment by sakyb7** [comment]
Im using ubuntu 18.04. Yes i ran the setup.sh script

**Comment by ChrisTruncer** [comment]
Hey, I just wanted to say that I just validated this issue and I am encountering the same thing. I will look into this.

A workaround for the time being is to use --headless instead of --web

**Comment by ChrisTruncer** [comment]
I just pushed a new update. Please do a git pull and re-run the setup script.

Thanks!

**Comment by sakyb7** [comment]
I am still facing some issue

Command:
` ./EyeWitness.py -f ~/site.com --web`

![screenshot from 2018-09-29 19-18-20](https://user-images.githubusercontent.com/42310984/46246516-bf280700-c41c-11e8-8301-6584382d5edc.png)

`./EyeWitness.py -f ~/site.com --headless`

![screenshot from 2018-09-29 19-18-10](https://user-images.githubusercontent.com/42310984/46246520-d830b800-c41c-11e8-95a7-bf6a170c40ed.png)

**Comment by sakyb7** [comment]
Any update???

**Comment by ChrisTruncer** [comment]
@sakyb7 - Being pushy does not make other people work faster, I would like you to please be patient while this is reviewed.

**Comment by sakyb7** [comment]
Yes sir.... thanks for your awesome support!

**Comment by ChrisTruncer** [comment]
I just downloaded a clean Ubuntu 18.04 VM and installed EyeWitness (after cloning from Github) and ran the setup script. I then provided a file and told EyeWitness to screenshot URLs in the file with --web. EyeWitness worked perfectly and did not encounter any errors. I did not make any modifications, so I am inclined to believe this is something that is an issue with your local VM. Please try removing old files and re-installing, or try on a clean VM.

**Comment by paolodm** [comment]
Just wanted to add that I am also experiencing this issue on a fairly new Kali box. 

geckodriver is at 0.24.0 (2019-01-28)
Checked out commit is 902509ab2bd095d950d292c370959b3ea1f91ecf
Ran setup prior to running.

![Screen Shot 2019-04-14 at 7 04 03 PM](https://user-images.githubusercontent.com/247525/56100550-205e8600-5ee8-11e9-97e4-0e90a5f5554c.png)

**Comment by ChrisTruncer** [comment]
I again think this is an issue with a local install of the VM. I have a clean install of Kali I use for testing with no other software installed (other than what comes with Kali). I just installed EyeWitness and it could screenshot the website.

<img width="790" alt="Eyewitness" src="https://user-images.githubusercontent.com/1674822/56150578-6bba7800-5f6c-11e9-9909-9084176e84d5.png">

**Comment by paolodm** [comment]
So I dug into the code and found that Python was throwing the borking on [line 79 of selenium_module.py](https://github.com/FortyNorthSecurity/EyeWitness/blob/master/modules/selenium_module.py#L79).

![image](https://user-images.githubusercontent.com/247525/56175558-ad2b4180-5fc5-11e9-9ca4-3b67ab0b81ed.png)

Looking at geckodriver.log, it seemed that webdriver was using the kali-installed Firefox ESR. ESR doesn't have headless mode afaict:

![image](https://user-images.githubusercontent.com/247525/56175611-ebc0fc00-5fc5-11e9-938a-38b8bda1644b.png)

Did you perhaps override or upgrade the base installation of Firefox ESR?

**Comment by ChrisTruncer** [comment]
I literally just took the base xfce Kali image, and then installed EyeWitness on it. I didn't make any other modifications to the VM.

I also just looked, and I can successfully take a screenshot from Firefox-ESR

<img width="767" alt="firefox" src="https://user-images.githubusercontent.com/1674822/56176180-777f5c00-5fb7-11e9-8d18-8771718fc1ed.png">

**Comment by paolodm** [comment]
I downloaded the xfce version and verified that it *does* work in xfce! So something is wrong when running EyeWitness in one of the default Kali ISOs (I believe it is using Gnome). 

https://cdimage.kali.org/kali-2019.1a/kali-linux-2019.1a-amd64.iso is actual ISO that was causing issues. 

I can dig in later to see specifically what it is missing. Running firefox-esr headless gave a specific error which I can dig into.

**Comment by Splint3r7** [comment]
For me, this solution worked!

`pip install selenium==2.53.6`
`python EyeWitness.py -f file.txt --only-ports 80,443 --web`.

**Comment by eybolo** [comment]
> ¡Para mí, esta solución funcionó!
> 
> `pip install selenium==2.53.6`
> `python EyeWitness.py -f file.txt --only-ports 80,443 --web`.

Exelente!! realmente esto me trajo la solucion. Gracias!!
